# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetStatus',
            fields=[
                ('targetID', models.IntegerField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=20)),
                ('annotation', models.CharField(max_length=512)),
                ('species', models.CharField(max_length=101)),
                ('status', models.CharField(max_length=50)),
                ('clone', models.CharField(max_length=13)),
                ('protein', models.CharField(max_length=13)),
                ('genePage', models.CharField(max_length=67)),
                ('uniprot', models.CharField(max_length=50)),
                ('taxonClass', models.CharField(max_length=50)),
                ('superkingdom', models.CharField(max_length=50)),
                ('targetRole', models.CharField(max_length=512)),
                ('batch', models.CharField(max_length=256)),
                ('community', models.CharField(max_length=8)),
                ('maxCode', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'SSGCIDPWS_NIAIDTargetStatusReport',
            },
        ),
    ]
